import React from 'react';
import { Link } from 'react-router-dom';
import { useData } from '../contexts/DataContext';
import { ArrowRight, History, Clock, FileText, Activity } from 'lucide-react';
import Card from '../components/ui/Card';
import Badge from '../components/ui/Badge';
import EmptyState from '../components/ui/EmptyState';

const AnalysesList = () => {
  const { history, isRefreshing, refreshError } = useData();

  if (refreshError && history.length === 0) {
    return (
      <div className="max-w-7xl mx-auto w-full px-4 py-12">
        <div className="mb-6 flex items-center justify-between">
          <h1 className="text-2xl font-bold text-[var(--bs-text-primary)]">All Analyses</h1>
        </div>
        <Card className="p-12 border-[var(--bs-status-critical-border)]">
          <EmptyState 
            icon={History} 
            title="No analysis history available" 
            description="Backend is currently unavailable and no previously synchronized history is stored on this browser."
          />
        </Card>
      </div>
    );
  }

  if (isRefreshing && history.length === 0) {
    return (
      <div className="max-w-7xl mx-auto w-full px-4 py-12">
        <div className="mb-6 flex items-center justify-between">
          <h1 className="text-2xl font-bold text-[var(--bs-text-primary)]">All Analyses</h1>
        </div>
        <Card className="p-12 flex items-center justify-center">
          <div className="animate-pulse flex flex-col items-center">
            <div className="h-8 w-8 bg-[var(--bs-border-light)] rounded-full mb-3"></div>
            <div className="h-3 w-32 bg-[var(--bs-border-light)] rounded mb-2"></div>
            <div className="h-2 w-24 bg-[var(--bs-border-light)] rounded"></div>
          </div>
        </Card>
      </div>
    );
  }

  if (!history || history.length === 0) {
    return (
      <div className="max-w-7xl mx-auto w-full px-4 py-12">
        <div className="mb-6 flex items-center justify-between">
          <h1 className="text-2xl font-bold text-[var(--bs-text-primary)]">All Analyses</h1>
        </div>
        <Card className="p-12">
          <EmptyState 
            icon={History} 
            title="No analyses found" 
            description="Start a new analysis to see it appear here."
          />
        </Card>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto w-full px-4 py-8">
      <div className="mb-8 flex items-end justify-between border-b border-[var(--bs-border-light)] pb-4">
        <div>
          <h1 className="text-3xl font-bold text-[var(--bs-text-primary)] tracking-tight">ANALYSES</h1>
          <p className="text-sm text-[var(--bs-text-secondary)] mt-2">
            History of all engineering intelligence reports and blueprints generated by BuildScout.
          </p>
        </div>
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {history.map((h) => {
          const score = h.validation_result?.overall_score ?? h.validation_score ?? 0;
          const status = (h.validation_result?.overall_status || h.validation_status || 'UNKNOWN').toLowerCase();
          
          let badgeStatus = 'neutral';
          if (status === 'pass') badgeStatus = 'success';
          if (status === 'warning') badgeStatus = 'warning';
          if (status === 'fail') badgeStatus = 'critical';
          
          const timeLabel = h.created_at 
            ? new Date(h.created_at).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' })
            : new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });
          
          const reqs = h.requirements_count ?? h.requirements?.length ?? 0;
          
          let reuseCount = 0;
          let adaptCount = 0;
          let buildCount = 0;
          const decisions = h.decisions || [];
          decisions.forEach(d => {
            const type = (d.decision || d.type || '').toUpperCase();
            if (type === 'REUSE') reuseCount++;
            if (type === 'ADAPT') adaptCount++;
            if (type === 'BUILD') buildCount++;
          });
          
          if (decisions.length === 0) {
             reuseCount = h.decision_summary?.reuse || 0;
             adaptCount = h.decision_summary?.adapt || 0;
             buildCount = h.decision_summary?.build || 0;
          }

          return (
            <Link 
              key={h.analysis_id} 
              to={`/analyses/${h.analysis_id}`}
              className="block group h-full"
            >
              <Card className="h-full p-5 hover:border-[var(--bs-orange-400)] hover:shadow-md transition-all flex flex-col relative overflow-hidden">
                <div className="absolute top-0 left-0 w-1 h-full bg-[var(--bs-border-light)] group-hover:bg-[var(--bs-orange-500)] transition-colors"></div>
                <div className="flex justify-between items-start mb-4">
                  <Badge status={badgeStatus} className="text-[10px] px-2 py-0.5">
                    {status.toUpperCase()}
                  </Badge>
                  <span className="flex items-center text-xs text-[var(--bs-text-tertiary)]">
                    <Clock className="w-3 h-3 mr-1"/> {timeLabel}
                  </span>
                </div>
                
                <h3 className="font-bold text-lg text-[var(--bs-text-primary)] mb-2 group-hover:text-[var(--bs-orange-500)] transition-colors line-clamp-2">
                  {h.domain || 'Unnamed Analysis'}
                </h3>
                
                <div className="mt-auto pt-4 border-t border-[var(--bs-border-light)] flex items-center justify-between">
                  <div className="flex items-center gap-3 text-xs text-[var(--bs-text-secondary)]">
                    <span className="flex items-center gap-1">
                      <FileText className="w-3 h-3" />
                      {reqs} Reqs
                    </span>
                    <span className="flex items-center gap-1">
                      <Activity className="w-3 h-3" />
                      {score}/100 Score
                    </span>
                  </div>
                  
                  <ArrowRight className="w-4 h-4 text-[var(--bs-text-tertiary)] group-hover:text-[var(--bs-orange-500)] transition-colors" />
                </div>
              </Card>
            </Link>
          );
        })}
      </div>
    </div>
  );
};

export default AnalysesList;
