"""
research.py — BuildSmart Research Agent.

Receives the functional components generated by DecompositionAgent.
For each component, issues targeted search queries via MCP tools 
(e.g., GitHub and Web Search) to find open-source candidates.
Uses the LLM to normalize the raw search results into structured candidates.
"""

import asyncio
import json
import logging
from typing import Any, Dict

from pydantic import BaseModel, Field

from agents.state import BuildSmartState
from config.settings import get_settings
from llm.client import get_llm
from llm.prompts import RESEARCH_SYSTEM_PROMPT
from mcp_integration.client import MCPToolClient

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Structured Output Models
# ---------------------------------------------------------------------------

class ResearchMetadata(BaseModel):
    stars: int | None = None
    language: str | None = None
    license: str | None = None
    last_updated: str | None = None


class ResearchCandidate(BaseModel):
    id: str
    component_id: str
    name: str
    source: str
    url: str
    description: str
    relevance_reason: str
    metadata: ResearchMetadata = Field(default_factory=ResearchMetadata)


class ResearchResult(BaseModel):
    candidates: list[ResearchCandidate]


# ---------------------------------------------------------------------------
# Agent Logic
# ---------------------------------------------------------------------------

class ResearchAgent:
    def __init__(self):
        self.settings = get_settings()
        self.llm = get_llm()
        # Use JSON mode for structural extraction
        self.llm_json = self.llm.bind(response_format={"type": "json_object"})

    async def _query_mcp_source(self, client: MCPToolClient, tool_name: str, args: Dict[str, Any]) -> str:
        """Helper to invoke an MCP tool and gracefully handle failures."""
        try:
            return await client.call_tool(tool_name, args)
        except Exception as e:
            logger.warning(f"MCP tool '{tool_name}' on '{client.name}' failed: {e}")
            return ""

    async def _find_tool_by_keyword(self, client: MCPToolClient, keywords: list[str]) -> str | None:
        """Dynamically discover a tool by matching keywords in its name."""
        try:
            tools = await client.list_tools()
            for tool in tools:
                name = tool.get("name", "").lower()
                if all(kw in name for kw in keywords):
                    return tool["name"]
        except Exception as e:
            logger.warning(f"Failed to list tools on '{client.name}': {e}")
        return None

    async def _research_component(
        self,
        component: Dict[str, Any],
        github_client: MCPToolClient | None,
        web_client: MCPToolClient | None,
    ) -> list[Dict[str, Any]]:
        """Research a single component and return normalized candidate dicts."""
        comp_id = component.get("id")
        comp_name = component.get("name", "")
        comp_desc = component.get("description", "")
        
        # Simple dynamic query formulation based on component details
        query = f"open source {comp_name.replace('_', ' ').lower()} {comp_desc}"
        # Keep query concise to improve search results
        query = " ".join(query.split()[:8])
        
        raw_results = []
        
        # Query GitHub MCP
        if github_client:
            tool_name = await self._find_tool_by_keyword(github_client, ["search", "repositories"])
            if not tool_name:
                tool_name = "search_repositories" # Fallback
            gh_result = await self._query_mcp_source(
                github_client, 
                tool_name, 
                {"query": query}
            )
            if gh_result:
                raw_results.append(f"--- GITHUB RESULTS ---\n{gh_result}")
                
        # Query Web MCP
        if web_client:
            tool_name = await self._find_tool_by_keyword(web_client, ["search"])
            if not tool_name:
                tool_name = "brave_web_search" # Fallback
            web_result = await self._query_mcp_source(
                web_client, 
                tool_name, 
                {"query": query + " github"}
            )
            if web_result:
                raw_results.append(f"--- WEB RESULTS ---\n{web_result}")
                
        if not raw_results:
            return []
            
        combined_raw = "\n\n".join(raw_results)
        
        # Use LLM to extract structured candidates from raw text
        prompt_content = (
            f"{RESEARCH_SYSTEM_PROMPT}\n\n"
            f"Component ID: {comp_id}\n"
            f"Component Name: {comp_name}\n"
            f"Component Description: {comp_desc}\n\n"
            f"Raw Search Results:\n{combined_raw}"
        )
        
        try:
            response = await self.llm_json.ainvoke(prompt_content)
            result_json = response.content
            parsed = ResearchResult.model_validate_json(result_json)
            # Serialize back to dicts to match state contract
            return [c.model_dump() for c in parsed.candidates]
        except Exception as e:
            logger.error(f"Failed to normalize research for {comp_id}: {e}")
            return []

    def run(self, state: BuildSmartState) -> BuildSmartState:
        """Execute the ResearchAgent synchronously.
        
        Because LangGraph nodes in our current setup run synchronously, 
        we use asyncio.run() to drive the async MCP and LLM calls.
        """
        return asyncio.run(self._arun(state))

    async def _arun(self, state: BuildSmartState) -> BuildSmartState:
        state["status"] = "RESEARCHING"
        components = state.get("components", [])
        
        # Setup MCP clients
        github_client = None
        if self.settings.mcp_github_command:
            github_client = MCPToolClient(self.settings.mcp_github_command, "github")
            
        web_client = None
        if self.settings.mcp_web_command:
            web_client = MCPToolClient(self.settings.mcp_web_command, "web")
            
        all_candidates = []
        seen_urls = set()
        
        # To avoid being rate limited and for V1 scope, process sequentially or in limited batches
        for comp in components:
            comp_candidates = await self._research_component(comp, github_client, web_client)
            
            # Deduplicate by URL
            for cand in comp_candidates:
                url = cand.get("url", "").strip().lower()
                if url and url not in seen_urls:
                    seen_urls.add(url)
                    all_candidates.append(cand)
                    
        # Update State
        state["candidates"] = all_candidates
        state["status"] = "RESEARCHED"
        state["current_agent"] = "ResearchAgent"
        
        history = state.get("agent_history", [])
        history.append("ResearchAgent")
        state["agent_history"] = history
        
        return state
