"""
research.py — BuildSmart Research Agent.

Receives the functional components generated by DecompositionAgent.
For each component, issues targeted search queries via MCP tools 
(e.g., GitHub and Web Search) to find open-source candidates.
Uses the LLM to normalize the raw search results into structured candidates.
"""

import asyncio
import json
import logging
from typing import Any, Dict

from pydantic import BaseModel, Field

from agents.state import BuildSmartState
from config.settings import get_settings
from llm.client import get_llm
from llm.prompts import RESEARCH_SYSTEM_PROMPT
from llm.retry import ainvoke_with_retry
from tools.gateway import tool_gateway

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Structured Output Models
# ---------------------------------------------------------------------------

class ResearchCandidate(BaseModel):
    id: str
    component_id: str
    name: str
    source: str
    url: str
    description: str
    relevance_reason: str
    metadata: Dict[str, Any] = Field(default_factory=dict)


class ResearchResult(BaseModel):
    candidates: list[ResearchCandidate]


# ---------------------------------------------------------------------------
# Agent Logic
# ---------------------------------------------------------------------------

class ResearchAgent:
    def __init__(self):
        self.settings = get_settings()
        self.llm = get_llm()
        # Use JSON mode for structural extraction
        self.llm_json = self.llm

    async def _research_component(
        self,
        component: Dict[str, Any],
        domain: str = "",
        requirements: list[Dict[str, Any]] = None,
        analysis_id: str = "unknown"
    ) -> tuple[list[Dict[str, Any]], list[Dict[str, Any]]]:
        """Research a single component and return normalized candidate dicts + traces."""
        import re
        def clean_text(text: str) -> str:
            if not text: return ""
            cleaned = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
            return " ".join(cleaned.split())

        comp_id = component.get("id")
        comp_name_raw = component.get("name", "").replace("_", " ")
        comp_name = clean_text(comp_name_raw).lower()
        comp_desc = component.get("description", "")
        category = component.get("category", "").upper()
        
        # Extract critical technology constraints from requirements
        reqs = requirements or []
        tech_keywords = {"aws": "AWS", "azure": "Azure", "gcp": "GCP", "google cloud": "GCP", "python": "Python", "node": "Node.js", "java": "Java", "go": "Go"}
        constraints = set()
        for r in reqs:
            desc_lower = r.get("description", "").lower()
            for kw, proper in tech_keywords.items():
                if kw in desc_lower:
                    constraints.add(proper)
        
        constraint_str = " ".join(constraints)
        
        domain_clean = clean_text(domain).lower()
        domain_clean = " ".join(domain_clean.split()[:3]) # Limit domain length
        domain_str = f"for {domain_clean}" if domain_clean else ""
        
        # Formulate specific queries per capability
        queries = {
            "github.search": f"{comp_name} open source {constraint_str}".strip(),
            "web.search": f"open source {comp_name} alternatives {constraint_str} {domain_str}".strip(),
            "aws.documentation": f"AWS {comp_name} architecture {domain_str}".strip(),
            "cloud.architecture": f"{constraint_str} {comp_name} reference architecture {domain_str}".strip()
        }
        
        traces = []
        raw_results = []
        
        # Capability Mapping (Removed license.get and security.get which are invalid here)
        capabilities = []
        if "CLOUD" in category or "INFRASTRUCTURE" in category:
            capabilities = ["cloud.architecture", "aws.documentation", "github.search", "web.search"]
        else:
            capabilities = ["github.search", "web.search"]

        async def fetch_cap(cap: str):
            query = queries.get(cap, comp_name)
            args = {
                "query": query,
                "limit": 10
            }
            if cap == "github.search":
                args["repository"] = query # github.search accepts repository as an alias for query in our adapter
                
            logger.info(f"ResearchAgent executing capability: {cap} for {comp_id} with query: {query}")
            try:
                return cap, await tool_gateway.execute_tool(cap, args)
            except Exception as e:
                logger.warning(f"Capability {cap} failed for {comp_id}: {e}")
                return cap, None

        tasks = [fetch_cap(cap) for cap in capabilities]
        gathered = await asyncio.gather(*tasks)

        for cap, trace in gathered:
            if not trace: continue
            traces.append(trace)
            
            if trace["status"] == "SUCCESS" and trace.get("results"):
                results = trace["results"]
                
                valid_items = []
                for res in results:
                    if isinstance(res, str):
                        if res.strip():
                            valid_items.append(res)
                    else:
                        if res:
                            valid_items.append(res)
                            
                if valid_items:
                    for item in valid_items:
                        raw_results.append({
                            "_tool": cap.upper(),
                            "_provider": trace.get('provider', 'UNKNOWN'),
                            "data": item
                        })

        if not raw_results:
            return [], traces
            
        # Context-size protection: Structure-aware compaction
        # We deduplicate by URL first to save space
        seen_compaction_urls = set()
        compacted_results = []
        
        def recursive_truncate(obj, depth=0):
            if depth > 10: return
            if isinstance(obj, dict):
                for k, v in obj.items():
                    if isinstance(v, str) and len(v) > 300:
                        obj[k] = v[:300] + "... [TRUNCATED]"
                    else:
                        recursive_truncate(v, depth + 1)
            elif isinstance(obj, list):
                if len(obj) > 15:
                    del obj[15:]
                for item in obj:
                    recursive_truncate(item, depth + 1)

        # Unpack nested MCP arrays to ensure budget operates on individual results
        flattened_results = []
        for wrapper in raw_results:
            data = wrapper["data"]
            if isinstance(data, str):
                try:
                    data = json.loads(data)
                except Exception:
                    pass
            
            if isinstance(data, dict):
                if "items" in data and isinstance(data["items"], list):
                    for item in data["items"]:
                        flattened_results.append({"_tool": wrapper["_tool"], "_provider": wrapper["_provider"], "data": item})
                    continue
                elif "results" in data and isinstance(data["results"], list):
                    for item in data["results"]:
                        flattened_results.append({"_tool": wrapper["_tool"], "_provider": wrapper["_provider"], "data": item})
                    continue
                    
            flattened_results.append({"_tool": wrapper["_tool"], "_provider": wrapper["_provider"], "data": data})

        for wrapper in flattened_results:
            data = wrapper["data"]
            
            # Attempt to extract URL for deduplication
            url = ""
            if isinstance(data, dict):
                url = data.get("url") or data.get("html_url") or ""
            
            url = str(url).strip().lower()
            if url and url in seen_compaction_urls:
                continue
            if url:
                seen_compaction_urls.add(url)
                
            # Intelligently truncate any verbose text fields inside the dict recursively
            if isinstance(data, str) and len(data) > 10000:
                wrapper["data"] = data[:10000] + "... [TRUNCATED]"
            else:
                recursive_truncate(data)
                        
            compacted_results.append(wrapper)

        # Build combined raw string, stopping if we exceed budget, ensuring valid JSON objects
        final_string_parts = []
        current_len = 0
        budget = 14000
        
        raw_candidates_count = len(compacted_results)
        
        for wrapper in compacted_results:
            part_str = json.dumps(wrapper, indent=2)
            if current_len + len(part_str) > budget:
                logger.warning(f"Context budget reached ({current_len} chars) for {comp_id}. Dropping remaining {len(compacted_results) - len(final_string_parts)} lower-ranked results.")
                break
            final_string_parts.append(part_str)
            current_len += len(part_str)
            
        combined_raw = "\n\n".join(final_string_parts)
        
        # Use LLM to extract structured candidates from raw text
        prompt_content = (
            f"{RESEARCH_SYSTEM_PROMPT}\n\n"
            f"Component ID: {comp_id}\n"
            f"Component Name: {comp_name}\n"
            f"Component Description: {comp_desc}\n\n"
            f"Raw Search Results:\n{combined_raw}"
        )
        
        # Wrapper to enforce JSON parsing inside the retry loop
        import re
        from langchain_core.messages import AIMessage
        
        async def validated_llm_invoke(*args, **kwargs):
            resp = await self.llm_json.ainvoke(*args, **kwargs)
            result_json = resp.content
            if isinstance(result_json, str):
                result_json = result_json.strip()
                # Find the first { or [ to ignore leading prose
                start_idx = result_json.find('{')
                start_arr_idx = result_json.find('[')
                if start_idx == -1 and start_arr_idx == -1:
                    pass # let it fail naturally
                else:
                    if start_idx != -1 and (start_arr_idx == -1 or start_idx < start_arr_idx):
                        result_json = result_json[start_idx:]
                    else:
                        result_json = result_json[start_arr_idx:]
                    
                # Find the last } or ] to ignore trailing prose
                end_idx = result_json.rfind('}')
                end_arr_idx = result_json.rfind(']')
                if end_idx != -1 or end_arr_idx != -1:
                    if end_idx != -1 and (end_arr_idx == -1 or end_idx > end_arr_idx):
                        result_json = result_json[:end_idx+1]
                    else:
                        result_json = result_json[:end_arr_idx+1]
                    
            # This will raise ValidationError if invalid, triggering the retry!
            try:
                parsed = ResearchResult.model_validate_json(result_json)
            except Exception as parse_exc:
                # Wrap the pydantic validation error so the retry handler thinks it's a 429 transient error
                class TransientValidationError(Exception):
                    status_code = 429
                raise TransientValidationError(f"JSON Parse Error: {parse_exc}") from parse_exc
                
            # Stash the parsed object in a custom attribute to avoid re-parsing
            resp.parsed_object = parsed
            return resp

        try:
            response = await ainvoke_with_retry(
                llm_callable=validated_llm_invoke,
                messages=prompt_content,
                agent_name="ResearchAgent",
                analysis_id=analysis_id,
                context_compactor=lambda msgs, limit: (
                    msgs[:limit] + "\n... [TRUNCATED for Retry]" if isinstance(msgs, str) else msgs
                )
            )
            parsed = getattr(response, "parsed_object", None)
            if not parsed:
                return [], traces
            
            final_candidates = [c.model_dump() for c in parsed.candidates]
            
            # Add the LLM trace metric
            traces.append({
                "tool_name": "ResearchAgent",
                "provider": "LLM",
                "status": "SUCCESS",
                "results": [],
                "metadata": {
                    "raw_candidates": len(raw_results),
                    "deduplicated": raw_candidates_count,
                    "selected": len(final_candidates)
                }
            })
            
            return final_candidates, traces
        except Exception as e:
            logger.error(f"Failed to normalize research for {comp_id}: {e}")
            return [], traces

    def run(self, state: BuildSmartState) -> BuildSmartState:
        """Execute the ResearchAgent synchronously.
        
        Because LangGraph nodes in our current setup run synchronously, 
        we use asyncio.run() to drive the async MCP and LLM calls.
        """
        return asyncio.run(self._arun(state))

    async def _arun(self, state: BuildSmartState) -> BuildSmartState:
        state["status"] = "RESEARCHING"
        analysis_id = state.get("analysis_id", "unknown")
        components = state.get("components", [])
            
        all_candidates = []
        seen_urls = set()
        agent_traces = []
        
        # Bounded concurrency for components
        RESEARCH_CONCURRENCY = getattr(self.settings, "research_concurrency", 4)
        semaphore = asyncio.Semaphore(RESEARCH_CONCURRENCY)
        
        async def process_comp(comp):
            async with semaphore:
                logger.info(f"ResearchAgent researching component: {comp.get('name')}")
                return await self._research_component(
                    comp, 
                    domain=state.get("domain", ""), 
                    requirements=state.get("requirements", []), 
                    analysis_id=analysis_id
                )

        tasks = [process_comp(comp) for comp in components]
        # Gather maintains order of the original components list
        results = await asyncio.gather(*tasks)
        
        for comp_candidates, traces in results:
            agent_traces.extend(traces)
            
            # 1. Deduplicate per component
            comp_unique = {}
            for cand in comp_candidates:
                url = cand.get("url", "").strip().lower()
                if url.endswith(".git"):
                    url = url[:-4]
                if url.endswith("/"):
                    url = url[:-1]
                
                name_source = f"{cand.get('name', '').strip().lower()}_{cand.get('source', '').strip().lower()}"
                key = url if url else name_source
                
                if key in comp_unique:
                    # Merge: prefer the one with more metadata
                    existing = comp_unique[key]
                    if len(cand.get("metadata", {})) > len(existing.get("metadata", {})):
                        comp_unique[key] = cand
                else:
                    comp_unique[key] = cand
                    
            unique_cands = list(comp_unique.values())
            
            # 2. Deterministic Ranking
            def score_candidate(c):
                score = 0
                meta = c.get("metadata", {})
                signals = []
                
                if c.get("url"): 
                    score += 10
                    signals.append("valid url")
                if c.get("relevance_reason"):
                    score += 10
                    signals.append("relevance mapped")
                
                # Metadata signals
                if meta.get("stars", 0) or meta.get("stargazers_count", 0):
                    score += 5
                    signals.append("stars")
                if meta.get("forks", 0):
                    score += 5
                    signals.append("forks")
                if meta.get("updated_at") or meta.get("last_commit"):
                    score += 5
                    signals.append("recent activity")
                if meta.get("language"):
                    score += 5
                    signals.append("language match")
                    
                c["_rank_score"] = score
                c["_rank_signals"] = ", ".join(signals) if signals else "basic extracted"
                return score
                
            unique_cands.sort(key=score_candidate, reverse=True)
            
            # 3. Shortlist top N
            SHORTLIST_SIZE = getattr(self.settings, "shortlist_size", 5)
            
            for i, cand in enumerate(unique_cands):
                cand["id"] = f"CAND-{len(all_candidates) + 1:03d}"
                
                # Cleanup temporary fields
                signals = cand.pop("_rank_signals", "unknown")
                score = cand.pop("_rank_score", 0)
                
                if i < SHORTLIST_SIZE:
                    cand["status"] = "shortlisted"
                    cand["shortlist_reason"] = f"Ranked {i+1} (Score: {score}). Signals: {signals}"
                else:
                    cand["status"] = "discovered"
                    cand["shortlist_reason"] = f"Ranked below top {SHORTLIST_SIZE} (Score: {score})."
                    
                all_candidates.append(cand)
                
        # Store traces
        if "traces" not in state:
            state["traces"] = []
            
        state["traces"].append({
            "agent_name": "ResearchAgent",
            "status": "SUCCESS",
            "execution_order": len(state["traces"]) + 1,
            "tool_calls": agent_traces
        })
                    
        # Update State
        state["candidates"] = all_candidates
        state["status"] = "RESEARCHED"
        state["current_agent"] = "ResearchAgent"
        
        history = state.get("agent_history", [])
        history.append("ResearchAgent")
        state["agent_history"] = history
        
        return state
