"""
research.py — BuildSmart Research Agent.

Receives the functional components generated by DecompositionAgent.
For each component, issues targeted search queries via MCP tools 
(e.g., GitHub and Web Search) to find open-source candidates.
Uses the LLM to normalize the raw search results into structured candidates.
"""

import asyncio
import json
import logging
from typing import Any, Dict

from pydantic import BaseModel, Field

from agents.state import BuildSmartState
from config.settings import get_settings
from llm.client import get_llm
from llm.prompts import RESEARCH_SYSTEM_PROMPT
from tools.github import search_github
from tools.web_search import search_web

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Structured Output Models
# ---------------------------------------------------------------------------

class ResearchMetadata(BaseModel):
    stars: int | None = None
    language: str | None = None
    license: str | None = None
    last_updated: str | None = None


class ResearchCandidate(BaseModel):
    id: str
    component_id: str
    name: str
    source: str
    url: str
    description: str
    relevance_reason: str
    metadata: ResearchMetadata = Field(default_factory=ResearchMetadata)


class ResearchResult(BaseModel):
    candidates: list[ResearchCandidate]


# ---------------------------------------------------------------------------
# Agent Logic
# ---------------------------------------------------------------------------

class ResearchAgent:
    def __init__(self):
        self.settings = get_settings()
        self.llm = get_llm()
        # Use JSON mode for structural extraction
        self.llm_json = self.llm.bind(response_format={"type": "json_object"})

    async def _research_component(
        self,
        component: Dict[str, Any]
    ) -> tuple[list[Dict[str, Any]], list[Dict[str, Any]]]:
        """Research a single component and return normalized candidate dicts + traces."""
        comp_id = component.get("id")
        comp_name = component.get("name", "")
        comp_desc = component.get("description", "")
        
        # Simple dynamic query formulation based on component details
        query = f"{comp_name.replace('_', ' ').lower()} {comp_desc}"
        # Keep query concise to improve search results
        query = " ".join(query.split()[:8])
        
        raw_results = []
        traces = []
        
        # Query GitHub MCP via tools adapter
        try:
            trace = await search_github(query=query, per_page=5)
            traces.append(trace)
            
            if trace["status"] == "SUCCESS" and trace["result_summary"].get("content"):
                raw_results.append(f"--- GITHUB RESULTS ---\n{trace['result_summary']['content']}")
        except Exception as e:
            # MCPManager handles timeouts and configuration errors gracefully via exceptions,
            # but we catch them here so ResearchAgent doesn't crash the workflow.
            logger.warning(f"GitHub MCP research failed for {comp_id}: {e}")

        # Query Tavily MCP via tools adapter
        try:
            trace = await search_web(
                query=query + " open source architecture github",
                search_depth="advanced",
                max_results=5
            )
            traces.append(trace)
            
            if trace["status"] == "SUCCESS" and trace["result_summary"].get("content"):
                raw_results.append(f"--- WEB RESULTS ---\n{trace['result_summary']['content']}")
        except Exception as e:
            logger.warning(f"Tavily MCP research failed for {comp_id}: {e}")
                
        if not raw_results:
            return [], traces
            
        combined_raw = "\n\n".join(raw_results)
        
        # Use LLM to extract structured candidates from raw text
        prompt_content = (
            f"{RESEARCH_SYSTEM_PROMPT}\n\n"
            f"Component ID: {comp_id}\n"
            f"Component Name: {comp_name}\n"
            f"Component Description: {comp_desc}\n\n"
            f"Raw Search Results:\n{combined_raw}"
        )
        
        try:
            response = await self.llm_json.ainvoke(prompt_content)
            result_json = response.content
            parsed = ResearchResult.model_validate_json(result_json)
            # Serialize back to dicts to match state contract
            return [c.model_dump() for c in parsed.candidates], traces
        except Exception as e:
            logger.error(f"Failed to normalize research for {comp_id}: {e}")
            return [], traces

    def run(self, state: BuildSmartState) -> BuildSmartState:
        """Execute the ResearchAgent synchronously.
        
        Because LangGraph nodes in our current setup run synchronously, 
        we use asyncio.run() to drive the async MCP and LLM calls.
        """
        return asyncio.run(self._arun(state))

    async def _arun(self, state: BuildSmartState) -> BuildSmartState:
        state["status"] = "RESEARCHING"
        components = state.get("components", [])
            
        all_candidates = []
        seen_urls = set()
        agent_traces = []
        
        # To avoid being rate limited and for V1 scope, process sequentially or in limited batches
        for comp in components:
            comp_candidates, traces = await self._research_component(comp)
            agent_traces.extend(traces)
            
            # Deduplicate by URL
            for cand in comp_candidates:
                url = cand.get("url", "").strip().lower()
                if url and url not in seen_urls:
                    seen_urls.add(url)
                    all_candidates.append(cand)
                    
        # Store traces
        if "traces" not in state:
            state["traces"] = []
            
        state["traces"].append({
            "agent_name": "ResearchAgent",
            "status": "SUCCESS",
            "execution_order": len(state["traces"]) + 1,
            "tool_calls": agent_traces
        })
                    
        # Update State
        state["candidates"] = all_candidates
        state["status"] = "RESEARCHED"
        state["current_agent"] = "ResearchAgent"
        
        history = state.get("agent_history", [])
        history.append("ResearchAgent")
        state["agent_history"] = history
        
        return state
